language: go

go:
  - 1.4
  - 1.3
  - 1.2
  - tip

go_import_path: github.com/google/gofuzz

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1

install:
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
  - go test -cover
  - go mod download && golangci-lint run --tests=false
